### ISSUE TITLE
2023知识竞赛题库JS有人做好了，大神快更新

### ISSUE THREAD

**Issue by hmjz100** [FoliageOwO/QingJiaoHelper#10]
2023知识竞赛题库JS有人做好了，大神快更新，老师等着用
题库JS：https://greasyfork.org/zh-CN/scripts/480858-lib-2023-2class

**Comment by hmjz100** [comment]
自己基于 https://greasyfork.org/zh-CN/scripts/480858-lib-2023-2class 做了一个优化版的题库：
https://greasyfork.org/zh-CN/scripts/480227-lib2classfix/
还有顺便改了一下作者的原脚本，增加支持了知识竞赛
https://greasyfork.org/zh-CN/scripts/480897-qingjiaohelper

**Comment by WindLeaf233** [comment]
@hmjz100 加一下 QQ：3584033226，望合作

**Comment by hmjz100** [comment]
另外说一声，有关**今年知识竞赛这部分的自动答题我也没测试过**（**今年知识竞赛不在青骄举行，而是在各省公众号**），不过那几个自动点击的元素（指``` "#app > div > div.home-container > div > div > div.competiotion-exam-box-all > div.exam-box > div > div.exam_content_bottom_btn > button", "#app > div > div.home-container > div > div > div.competiotion-exam-box-all > div.exam-box > div.competition-sub > button", "#app > div > div.home-container > div > div > div.competiotion-exam-box-all > div.exam-box > div.competition-sub > button.ant-btn.ant-btn-primary" ```）是**取自于您脚本的0.2.8旧版**

相关旧版代码：
```
...
function next(answers, btn=null) {
      runWhenReady('.exam-content-question', questionElement => {
        let question = questionElement.innerText;
        question = removeSpaces(question.split('\n')[0]); // get the first line
        console.debug(question);
 
        if (!started) {
          runWhenReady('#app > div > div.home-container > div > div > div.competiotion-exam-box-all > div.exam-box > div.competition-sub > button', element => {
            started = true;
            next(answers, element);
          });
        } else {
          if (count > 0) {
            btn = document.querySelector('#app > div > div.home-container > div > div > div.competiotion-exam-box-all > div.exam-box > div.competition-sub > button.ant-btn.ant-btn-primary');
          }
...
          let selects = document.getElementsByClassName('exam-single-content-box');
...
```
