### ISSUE TITLE
【Bug】自学课堂、课程中心 视频手动跳过后不会记录到“做任务攒学分”里

### ISSUE THREAD

**Issue by hmjz100** [FoliageOwO/QingJiaoHelper#13]
自学课堂、课程中心 视频手动点击跳过按钮后即使答了题不会记录到学分中心的“做任务攒学分”里
如上，所以建议js控制视频到结尾，这样“开始答题”按钮就会亮起，也会记录到学分中心

**Comment by elseif** [comment]
```javascript
$('video').player.trigger('ready')
$('video').player.trigger('ended')
```

**Comment by FoliageOwO** [comment]
这个脚本没使用 `jQuery`，目前采用了个很蠢的办法暂时修复了这个问题，似乎选中 `video` 元素后没办法控制他的播放和播放进度，只能让用户手动点一下播放才能自动跳转到最后
